---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content/chapter
  label: Chapter
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/ain/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.46'
