baseurl = "/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode = "en-us"
languageLang = "en"
title = "Crowdfunding Campaign Guide"
[author]
name = "Harry Cresswell"
[[menu.main]]
name = "01 – Home"
url = "#"
weight = 5
[[menu.main]]
name = "02 – Introduction"
url = "#introduction"
weight = 10
[[menu.main]]
name = "03 – Fundraising Strategy"
url = "#fundraising"
weight = 15
[[menu.main]]
name = "04 – Target Audience"
url = "#audience"
weight = 20
[[menu.main]]
name = "05 – Build your Stories"
url = "#stories"
weight = 25
[[menu.main]]
name = "06 – Marketing Channels"
url = "#marketing"
weight = 30
[[menu.main]]
name = "07 – Next Steps"
url = "#nextsteps"
weight = 35
[[menu.main]]
name = "08 – Resources"
url = "#resources"
weight = 40
[params]
cloudinary_url = "https://res.cloudinary.com/ain/image/upload"
description = "SeedTribe, Crowdfunding Guide"
keywords = "SeedTribe Crowdfunding Campaign Guide"
location = "London, UK"
strapline = "SeedTribe Crowdfunding Campaign Guide"
twitter = "@seedtribe"
[permalinks]
chapter = "/:section/:slug/"
page = "/:title/"
